version: '3.9'
services:
  mongo_db:
    container_name: mongo_95435
    image: mongo:latest
    ports: 
      - 27025:27017
  api:
    container_name: api_95435
    build: .
    ports: 
      - 8085:8080
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/admin
    depends_on:
      - mongo_db